### ISSUE TITLE
Higher resolutions

### ISSUE THREAD

**Issue by GhostlyDark** [Fanfreluche/SUPERMARIO64-hires-texture-pack#2]
Hello there,

any chance we can get higher resolution exports like 8x, 16x...?

I read that you made these in Inkscape. Is it possible to upload the SVG files on GitHub? This way anybody can export the text in any resolution needed.

Thank you for your effort :)

**Comment by Fanfreluche** [comment]
Hi,
I put the SVG file here: https://github.com/Fanfreluche/SUPERMARIO64-hires-texture-pack/blob/master/source.svg
I will export it in higher res but I don't know yet when :P

**Comment by GhostlyDark** [comment]
Thank you for uploading the SVG source. I was able to export everything, except for the Mario head. It's the only one missing :)
